export default function MockServer() {
  return (
    <article className="grid" style={{ gap: 16 }}>
      <h1>@hfsa/mock-server</h1>
      <p>
        CLI to run two services locally against your OpenAPI file:
      </p>
      <ul>
        <li><strong>Mock API</strong>: serves endpoints for rapid UI development.</li>
        <li><strong>Docs server</strong>: renders OpenAPI via Scalar for live reference.</li>
      </ul>
      <h2>Commands</h2>
      <pre className="card" style={{ overflowX: 'auto' }}>{`# from the repo root
pnpm -w --filter @hfsa/boilerplate run mock:api      # generate + start mock
pnpm -w --filter @hfsa/boilerplate run docs:api      # open API docs server

# or use the CLI directly from the package
# hfsa-mock mock --spec apps/boilerplate/public/openapi.yaml --port 4010
# hfsa-mock docs --spec apps/boilerplate/public/openapi.yaml --port 4011`}</pre>
      <p className="muted">OpenAPI is generated by <strong>@hfsa/openapi-ts</strong> from feature mocks.</p>
    </article>
  );
}

